[package]
name = "bluebird"
version = "0.1.0"
edition = "2021"

[dependencies]
tokio = { version = "1.0", features = ["full"] }
tokio-stream = "0.1"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
signal-hook = "0.3"
toml = "0.5"
dirs = "4.0"
andthe = { path = "../andthe" }

